export const HOME = '/'
export const AUTHOR = '/authors'
export const AUTHORS = '/authors/'
export const AUTHORS_EXT = ''
export const SERIE = '/series'
export const SERIES = '/series/'
export const SERIES_EXT = ''
